"""initial control center schema

Revision ID: 690c18a03d40
Revises: 
Create Date: 2026-08-17 00:59:57.788784
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '690c18a03d40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('object_type', sa.String(length=120), nullable=True),
    sa.Column('object_id', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_module'), 'audit_events', ['module'], unique=False)
    op.create_table('destination_lists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), server_default=sa.text("'custom'"), nullable=False),
    sa.Column('source_type', sa.String(length=32), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('update_mode', sa.String(length=32), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=40), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("kind IN ('rkn','custom','system')", name='ck_destination_lists_kind'),
    sa.CheckConstraint("source_type IN ('manual','url','file')", name='ck_destination_lists_source_type'),
    sa.CheckConstraint("update_mode IN ('manual','daily')", name='ck_destination_lists_update_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('computer_name', sa.String(length=63), nullable=True),
    sa.Column('assigned_ad_user', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pxe_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_assigned_ad_user'), 'devices', ['assigned_ad_user'], unique=False)
    op.create_index(op.f('ix_devices_computer_name'), 'devices', ['computer_name'], unique=False)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=True)
    op.create_table('docker_stacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('compose_path', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=32), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued','running','success','failed','cancelled')", name='ck_jobs_state'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_jobs_progress'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_module'), 'jobs', ['module'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('module_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'key', name='uq_module_settings_module_key')
    )
    op.create_table('os_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('architecture', sa.String(length=40), server_default=sa.text("'amd64'"), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('windows','linux')", name='ck_os_images_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_images_kind'), 'os_images', ['kind'], unique=False)
    op.create_table('service_cache',
    sa.Column('service_name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('service_name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('software_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('software_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=40), server_default=sa.text("'windows'"), nullable=False),
    sa.Column('package_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('install_args', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vpn_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=80), server_default=sa.text("'adguard'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('credential_ref', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('destination_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('destination_list_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('domain','ipv4','ipv6','cidr')", name='ck_destination_entries_type'),
    sa.ForeignKeyConstraint(['destination_list_id'], ['destination_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_list_id', 'entry_type', 'normalized_value', name='uq_destination_entry')
    )
    op.create_index(op.f('ix_destination_entries_destination_list_id'), 'destination_entries', ['destination_list_id'], unique=False)
    op.create_index(op.f('ix_destination_entries_entry_type'), 'destination_entries', ['entry_type'], unique=False)
    op.create_table('device_group_members',
    sa.Column('device_group_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_group_id', 'device_id')
    )
    op.create_table('internet_policies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('default_action', sa.String(length=20), server_default=sa.text("'direct'"), nullable=False),
    sa.Column('default_vpn_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone', sa.String(length=80), server_default=sa.text("'Europe/Moscow'"), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("default_action IN ('direct','vpn','block')", name='ck_internet_policies_default_action'),
    sa.ForeignKeyConstraint(['default_vpn_profile_id'], ['vpn_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proxy_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('listen_host', sa.String(length=64), server_default=sa.text("'127.0.0.1'"), nullable=False),
    sa.Column('listen_port', sa.Integer(), nullable=False),
    sa.Column('route_action', sa.String(length=20), server_default=sa.text("'direct'"), nullable=False),
    sa.Column('vpn_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("route_action IN ('direct','vpn')", name='ck_proxy_route_action'),
    sa.CheckConstraint('listen_port >= 1 AND listen_port <= 65535', name='ck_proxy_port'),
    sa.ForeignKeyConstraint(['vpn_profile_id'], ['vpn_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listen_host', 'listen_port', name='uq_proxy_listen'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pxe_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('os_image_id', sa.BigInteger(), nullable=True),
    sa.Column('computer_name', sa.String(length=63), nullable=True),
    sa.Column('windows_edition', sa.String(length=160), nullable=True),
    sa.Column('locale', sa.String(length=32), server_default=sa.text("'ru-RU'"), nullable=False),
    sa.Column('timezone', sa.String(length=80), server_default=sa.text("'Europe/Moscow'"), nullable=False),
    sa.Column('auto_install', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('domain_join', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['os_image_id'], ['os_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('quota_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('used_seconds', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('manual_bonus_seconds', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('used_seconds >= 0', name='ck_quota_usage_used'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'usage_date', name='uq_quota_usage_device_date')
    )
    op.create_index(op.f('ix_quota_usage_device_id'), 'quota_usage', ['device_id'], unique=False)
    op.create_index(op.f('ix_quota_usage_usage_date'), 'quota_usage', ['usage_date'], unique=False)
    op.create_table('software_group_members',
    sa.Column('software_group_id', sa.BigInteger(), nullable=False),
    sa.Column('software_item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['software_group_id'], ['software_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_item_id'], ['software_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('software_group_id', 'software_item_id')
    )
    op.create_table('traffic_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('traffic_date', sa.Date(), nullable=False),
    sa.Column('rx_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('tx_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('vpn_rx_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('vpn_tx_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'traffic_date', name='uq_traffic_daily_device_date')
    )
    op.create_index(op.f('ix_traffic_daily_device_id'), 'traffic_daily', ['device_id'], unique=False)
    op.create_index(op.f('ix_traffic_daily_traffic_date'), 'traffic_daily', ['traffic_date'], unique=False)
    op.create_table('internet_policy_devices',
    sa.Column('internet_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internet_policy_id'], ['internet_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internet_policy_id', 'device_id')
    )
    op.create_table('internet_policy_groups',
    sa.Column('internet_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('device_group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internet_policy_id'], ['internet_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internet_policy_id', 'device_group_id')
    )
    op.create_table('pxe_profile_software_groups',
    sa.Column('pxe_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('software_group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['pxe_profile_id'], ['pxe_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_group_id'], ['software_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pxe_profile_id', 'software_group_id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internet_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_list_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('vpn_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("action IN ('direct','vpn','block')", name='ck_routing_rules_action'),
    sa.ForeignKeyConstraint(['destination_list_id'], ['destination_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internet_policy_id'], ['internet_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vpn_profile_id'], ['vpn_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_destination_list_id'), 'routing_rules', ['destination_list_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_internet_policy_id'), 'routing_rules', ['internet_policy_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internet_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['internet_policy_id'], ['internet_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internet_policy_id', 'name', name='uq_schedule_policy_name')
    )
    op.create_index(op.f('ix_schedules_internet_policy_id'), 'schedules', ['internet_policy_id'], unique=False)
    op.create_table('time_quotas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('internet_policy_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=True),
    sa.Column('quota_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('quota_minutes >= 0', name='ck_time_quotas_minutes'),
    sa.CheckConstraint('weekday IS NULL OR (weekday >= 0 AND weekday <= 6)', name='ck_time_quotas_weekday'),
    sa.ForeignKeyConstraint(['internet_policy_id'], ['internet_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_quotas_internet_policy_id'), 'time_quotas', ['internet_policy_id'], unique=False)
    op.create_table('schedule_periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_schedule_periods_weekday'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_periods_schedule_id'), 'schedule_periods', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_periods_schedule_id'), table_name='schedule_periods')
    op.drop_table('schedule_periods')
    op.drop_index(op.f('ix_time_quotas_internet_policy_id'), table_name='time_quotas')
    op.drop_table('time_quotas')
    op.drop_index(op.f('ix_schedules_internet_policy_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_routing_rules_internet_policy_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_destination_list_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_table('pxe_profile_software_groups')
    op.drop_table('internet_policy_groups')
    op.drop_table('internet_policy_devices')
    op.drop_index(op.f('ix_traffic_daily_traffic_date'), table_name='traffic_daily')
    op.drop_index(op.f('ix_traffic_daily_device_id'), table_name='traffic_daily')
    op.drop_table('traffic_daily')
    op.drop_table('software_group_members')
    op.drop_index(op.f('ix_quota_usage_usage_date'), table_name='quota_usage')
    op.drop_index(op.f('ix_quota_usage_device_id'), table_name='quota_usage')
    op.drop_table('quota_usage')
    op.drop_table('pxe_profiles')
    op.drop_table('proxy_profiles')
    op.drop_table('internet_policies')
    op.drop_table('device_group_members')
    op.drop_index(op.f('ix_destination_entries_entry_type'), table_name='destination_entries')
    op.drop_index(op.f('ix_destination_entries_destination_list_id'), table_name='destination_entries')
    op.drop_table('destination_entries')
    op.drop_table('vpn_profiles')
    op.drop_table('software_items')
    op.drop_table('software_groups')
    op.drop_table('settings')
    op.drop_table('service_cache')
    op.drop_index(op.f('ix_os_images_kind'), table_name='os_images')
    op.drop_table('os_images')
    op.drop_table('module_settings')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_module'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('docker_stacks')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_computer_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_assigned_ad_user'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('device_groups')
    op.drop_table('destination_lists')
    op.drop_index(op.f('ix_audit_events_module'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
